# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
builds:
  - id: oapi-codegen
    main: ./cmd/oapi-codegen
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    goos:
      - linux
      - darwin
      - windows
archives:
  - format: binary
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
